#pragma once

#define RUNAS_USER_DEFAULT 2000
#define RUNAS_GROUP_DEFAULT 2000

#define LOG_LEVEL 250

#define SERVER_VERSION "v0.1"

#define CLIENTS_MAX 4096*2
#define NET_BACKLOG CLIENTS_MAX

#define SOCKET_RECEIVE_BUFFER_SIZE 4096
#define SOCKET_SEND_BUFFER_SIZE 4096

#define EPOLL_FD_COUNT_MAX 512

#define IDLE_SLEEP_MICROSECONDS 100

#define STATICFS_SUBDIR "/static"
#define BACKEND_ROOT_PATH "/backend"

#define CONFIG_FILE "/etc/falcon-http/config.json"
